version: "3"

services:
  zeppelin:
    image: apache/zeppelin:0.10.0
    platform:
      "linux/amd64"
    volumes:
      - notebook:/notebook
      - data:/data
    environment:
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
    ports:
      - "7077:7077"
      - "8080:8080"
      - "4040:4040"
    
volumes:
  notebook:
  data:
